import Config

# Configure your database
config :project, Todolist.Repo,
  username: "postgres",
  password: "postgres",
  database: "project_dev",
  hostname: "localhost",
  # username: "gfzskfbiamvxlc",
  # password: "372d1600949356f4854eef9c834a3ce1456f173d2bb673a0f334ee988057b869",
  # database: "dc56s5uk45nfe4",
  # hostname: "ec2-54-154-101-45.eu-west-1.compute.amazonaws.com",
  show_sensitive_data_on_connection_error: true,
  # ssl: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :project, TodolistWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {134, 209, 31, 125}, port: 4000],
  #  https: [
  #     port: 443,
  #     cipher_suite: :strong,
  #     keyfile: "priv/cert/selfsigned_key.pem",
  #     certfile: "priv/cert/selfsigned.pem"
  #   ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "3nbl5SOSXBavUDOzuRWDQYAVA0sIgXQaw6oLYXzXWRS5bi2c4ssXwOZ0DNBzdmAa",
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#

#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
